# ===== ENV =====
export ZDOTDIR="$HOME"
export PATH="/opt/homebrew/bin:$PATH"

# ===== PATH =====
export PATH="/opt/homebrew/bin:$PATH"

# Disable p10k wizard
export POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true

# Powerlevel10k theme
source ~/.config/powerlevel10k/powerlevel10k.zsh-theme
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

# Plugins
source ~/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.config/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Completion
autoload -Uz compinit
compinit

# ALIASES
alias ll='ls -lh'

# Go path
export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"
export PATH="/Users/alcantara/.config/herd-lite/bin:$PATH"
export PHP_INI_SCAN_DIR="/Users/alcantara/.config/herd-lite/bin:$PHP_INI_SCAN_DIR"

# Added by Antigravity
export PATH="/Users/alcantara/.antigravity/antigravity/bin:$PATH"

. "$HOME/.local/bin/env"

# Added by Windsurf
export PATH="/Users/alcantara/.codeium/windsurf/bin:$PATH"
